=pod

=head1 NAME 

F<BackupProg::Exception::BadArgument> - an exception used to tell a bad 
argument has been passed.

=head1 SYNOPSIS

In the class that throw it :

   throw BackupProg::Exception::BadArgument("A message");

In the class which could catch it :

   try{
	 $log = BackupProg::Common::Logger
	      ->instance( "backup_prog.log", LL_WARN, 25, LM_NEWFILE );
   }
   catch BackupProg::Exception::BadArgument with{
    	 my $E = shift;
	 print "in catch block\n";
    	 print "Error creating Logger : ".$E->message()."\n";
   };

=head1 DESCRIPTION

This is an exception used to throw a bad argument error.

=head1 CONSTRUCTOR

=over 4

=item message: F<string>

      The message that will be print in the exception.

=back

=head1 KNOWN BUGS

None.

=head1 SEE ALSO

See F<BackupProg::Exception::BaseException>, the class BadArgument inherits 
from.

=head1 COPYRIGHT

Licensed under the term of the GNU GPL v3.

=cut
