name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libcurses-perl liblocale-gettext-perl libdatetime-perl libtest2-suite-perl
        version: 1.0

    - name: perlPathVerbose
      run: perl -V
        
    - name: Generate Makefiles
      run: ./gen-makefiles.sh

    - name: Install
      run: make install

    - name: Run check
      run: make check
