=pod

=head1 NAME

F<BackupProg::UserInterface::WidgetList> is a list of widget with refresh
feature.

=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 CONSTANTS

=over 4

=item LogLevels

=item LogModes

=back

=head1 EXPORTED TAGS

=head1 CONSTRUCTOR

=over 4

Construct an empty list. Accept no paramater.

=back

=head1 METHODS

=over 4

=item len()

Return the length of the internal list as a scalar.

=item append()

Add the given Widget to the internal list.

=item refresh()

Refresh all widgets if needed. The needed is done by the widget's dirty flag
value.

=item force_refresh()

Call force_refresh() function on all widgets.

=back

=head1 KNOWN BUGS

=head1 SEE ALSO

=head1 AUTHOR

Jerome Pasquier <rainbru@free.fr>

=head1 COPYRIGHT

Licensed under the term of the GNU GPL v3.

=cut
